### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by gmcclins** [lrvick/rant#2]
pip install rant fails. There seems to be a problem with locating README.md

`Downloading rant-0.2.2.tar.gz

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-UlDDzM/rant/setup.py", line 14, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md`

**Comment by lrvick** [comment]
Known issue with 0.2.2

Please try 0.5 (not yet released in pip)

```
pip install --user --upgrade -e git+https://github.com/lrvick/rant/#egg=rant
```

**Comment by lrvick** [comment]
Closing as this does not seem reproducible in 0.5 but if you have any further issues lmk.
